// Generates src/environments/environment.ts and environment.prod.ts from
// process.env (Cloudflare Pages build variables in production, or a
// gitignored .env.local read via dotenv for local development). This
// replaces the Flutter app's anti-pattern of hardcoding the Supabase URL
// and anon key directly in main.dart.
import { config } from 'dotenv';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

config({ path: join(root, '.env.local') });

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error(
    '\n[generate-env] Missing SUPABASE_URL / SUPABASE_ANON_KEY.\n' +
      'Local dev: create a .env.local file (see .env.local.example).\n' +
      'Cloudflare Pages: set them under Settings -> Environment variables.\n'
  );
  process.exit(1);
}

const envDir = join(root, 'src', 'environments');
if (!existsSync(envDir)) mkdirSync(envDir, { recursive: true });

const contents = (production) => `// AUTO-GENERATED by scripts/generate-env.mjs — do not edit, do not commit.
export const environment = {
  production: ${production},
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
};
`;

writeFileSync(join(envDir, 'environment.ts'), contents(false));
writeFileSync(join(envDir, 'environment.prod.ts'), contents(true));

console.log('[generate-env] environment.ts / environment.prod.ts written.');
